[[main]]
name = "Home"
pageRef = "index"
weight = 1

[[main]]
name = "Games"
pageRef = "games"
weight = 10

# [[main]]
#   name = "Brick Gigil"
#   parent = "Games"
#   pageRef = "brick-gigil"
#   weight = 11

[[main]]
name = "About us"
pageRef = "about"
weight = 20